version: '3'
volumes:
  dados:


services:
  db:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD="postgres"
      - POSTGRES_HOST_AUTH_METHOD=trust #tira erro na autenticação do insert do postgres
    volumes:
      # Volume dos dados
      - dados:/var/lib/postgresql/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql #para permitir inicialização
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      #Configuração do Proxy Reverso
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    #networks:
    #  - web # seta que o serviço frotend só pertence a rede web
    #depends_on:
      #orquestar a inicialização do serviço
      - app
  app:
    image: python:3.6
    volumes:
      # Aplicação
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    ports:
      - 8080:8080
